apiVersion: apps/v1
kind: Deployment
metadata:
  name: oai-rru
  labels:
    app: oai-rru
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oai-rru
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: oai-rru
      annotations:
        k8s.v1.cni.cncf.io/networks: rru-net1
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: rf-device-type
                operator: In
                values:
                - "eutran"
      containers:
      - name: rru
        image: image-registry.openshift-image-registry.svc:5000/oai/oai-rru
        imagePullPolicy: Always
        #command: ['sh', '-c', 'sleep 60d00']
        securityContext:
          privileged: true
        ports:
        - containerPort: 50000
          name: if4p5-c
          protocol: UDP
        - containerPort: 50001
          name: if4p5-u
          protocol: UDP
        env:
          - name: RU_LOCAL_IF
            valueFrom:
              configMapKeyRef:
                name: rru-config
                key: ru_local_if
          - name: RU_LOCAL_IP
            valueFrom:
              configMapKeyRef:
                name: rru-config
                key: ru_local_ip
          - name: RU_REMOTE_IP
            valueFrom:
              configMapKeyRef:
                name: rru-config
                key: ru_remote_ip
          - name: BAND
            valueFrom:
              configMapKeyRef:
                name: rru-config
                key: band
      - name: tcpdump
        image: corfr/tcpdump
        command:
          - /bin/sleep
          - infinity
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: rru-sa
      terminationGracePeriodSeconds: 30
