apiVersion: v1
kind: Pod
metadata:
  name: cyclictest
  namespace: oai
spec:
  restartPolicy: Never
  containers:
  - name: cyclictest
    image:  docker.io/cscojianzhan/cyclictest
    # command: []
    # args: ["cyclictest", "--smp", "--priority=80", "--interval=200","--distance=0"]
    resources:
      limits:
        cpu: 4
        memory: "400Mi"
      requests:
        cpu: 4
        memory: "400Mi"
    env:
    - name: DURATION
      value: "2m"
    securityContext:
      privileged: true
      capabilities:
        add:
          - SYS_NICE
          - SYS_RAWIO
          - IPC_LOCK
    volumeMounts:
    - mountPath: /tmp
      name: results-volume
    - mountPath: /dev/cpu_dma_latency
      name: cstate
  nodeSelector:
    rf-device-type: "eutran"
  volumes:
  - name: results-volume
    hostPath:
      path: /tmp
  - name: cstate
    hostPath:
      path: /dev/cpu_dma_latency
